#!/bin/sh
#
# chkconfig: - 58 75
# description: data consumer cmos

. /etc/init.d/functions

EXEC=/opt/minard/bin/data_consumer_cmos
USER=minard
MINARD_SETTINGS=/etc/minard/settings.cfg

export MINARD_SETTINGS

WORKERS=8

case $1 in
    start)
	for i in `seq 1 $WORKERS`; do
	    echo -n "starting $EXEC"
	    LOGFILE=/var/log/minard/data_consumer_cmos_$i.log
	    daemon --user=$USER --check=$EXEC "nohup $EXEC > $LOGFILE 2>&1 &"
	    echo
	done
	;;
    stop)
	pkill -f $EXEC
	;;
    restart)
	$0 stop
	sleep 1
	$0 start
	;;
    *)
	echo "usage: $0 [start|stop|restart]"
	;;
esac
