#!/bin/sh
#
# chkconfig: - 58 74
# description: data producer

. /etc/init.d/functions

EXEC=/opt/minard/bin/data_producer
USER=minard
LOGFILE=/var/log/minard/data_producer.log
MINARD_SETTINGS=/etc/minard/settings.cfg

export MINARD_SETTINGS

case $1 in
    start)
	echo -n "starting $EXEC"
	daemon --user=$USER --check=$EXEC "nohup $EXEC > $LOGFILE 2>&1 &"
	echo
	;;
    stop)
	pkill -f $EXEC
	;;
    restart)
	$0 stop
	sleep 1
	$0 start
	;;
    *)
	echo "usage: $0 [start|stop|restart]"
	;;
esac
