#!/bin/sh
#
# chkconfig: - 58 74
# description: minard dispatch push

. /etc/init.d/functions

EXEC=/opt/minard/bin/minard_dispatch_push
USER=minard
LOGFILE=/var/log/minard/minard_dispatch_push.log

case $1 in
    start)
	daemon --user=$USER --check=$EXEC "nohup $EXEC > $LOGFILE 2>&1 &"
	echo
	;;
    stop)
	killall $EXEC
	;;
    restart)
	$0 stop
	sleep 1
	$0 start
    ;;
    *)
    echo "usage: $0 [start|stop|restart]"
    ;;
esac
