#!/bin/sh
#
# chkconfig: - 58 74
# description: minard dispatch pull

. /etc/init.d/functions

EXEC=/opt/minard/bin/minard_dispatch_pull
USER=minard

WORKERS=4

case $1 in
    start)
	for i in `seq 1 $WORKERS`; do
	    LOGFILE=/var/log/minard/minard_dispatch_pull_$i.log
	    daemon --user=$USER --check=$EXEC "nohup $EXEC > $LOGFILE 2>&1 &"
	    echo
	done
	;;
    stop)
	killall $EXEC
	;;
    restart)
	$0 stop
	sleep 1
	$0 start
    ;;
    *)
    echo "usage: $0 [start|stop|restart]"
    ;;
esac
