#!/bin/sh
#
# chkconfig: - 58 74
# description: orca consumer base

. /etc/init.d/functions

EXEC=/opt/minard/bin/orca_consumer_base
USER=minard

WORKERS=2

case $1 in
    start)
	for i in `seq 1 $WORKERS`; do
	    echo -n "starting $EXEC"
	    LOGFILE=/var/log/minard/orca_consumer_base_$i.log
	    daemon --user=$USER --check=$EXEC "nohup $EXEC > $LOGFILE 2>&1 &"
	    echo
	done
	;;
    stop)
	pkill -f $EXEC
	;;
    restart)
	$0 stop
	sleep 1
	$0 start
	;;
    *)
	echo "usage: $0 [start|stop|restart]"
	;;
esac
