#!/bin/sh
#
# chkconfig: - 58 74
# description: orca producer

. /etc/init.d/functions

EXEC=/opt/minard/bin/orca_producer
USER=minard
LOGFILE=/var/log/minard/orca_producer.log

case $1 in
    start)
	daemon --user=$USER --check=$EXEC "nohup $EXEC > $LOGFILE 2>&1 &"
	;;
    stop)
	killall $EXEC
	;;
    restart)
	$0 stop
	sleep 1
	$0 start
    ;;
    *)
    echo "usage: $0 [start|stop|restart]
    ;;
esac
