#!/bin/sh
#
# chkconfig: - 58 74
# description: orca consumer cmos

. /etc/init.d/functions

EXEC=/opt/minard/bin/orca_consumer_cmos
USER=minard

WORKERS=2

case $1 in
    start)
	for $i in `seq 1 $WORKERS`;
	    LOGFILE=/var/log/minard/orca_consumer_cmos_$i.log
	    daemon --user=$USER --check=$EXEC "nohup $EXEC > $LOGFILE 2>&1 &"
	done
	;;
    stop)
	killall $EXEC
	;;
    restart)
	$0 stop
	sleep 1
	$0 start
    ;;
    *)
    echo "usage: $0 [start|stop|restart]
    ;;
esac
