#!/usr/bin/env bash
set -e; sudo -v || exit

add_service () {
    # adds an init script service to chkconfig or update-rc.d
    if [ -f /etc/debian_version ]; then
        sudo update-rc.d $1 defaults
    elif [ -f /etc/redhat-release ]; then
        sudo chkconfig --add $1
        sudo chkconfig --level 2345 $1 on
    else
        echo "Error! Couldn't determine Linux distribution!"
        echo "no /etc/debian_version or /etc/redhat-release file"
        exit 1
    fi
}
    
if [ ! -f /usr/local/bin/redis-server ]; then
    # install redis to /usr/local
    printf "Installing redis..."
    cd /usr/local
    sudo curl -O -s http://download.redis.io/redis-stable.tar.gz
    sudo tar -xzf redis-stable.tar.gz
    cd redis-stable
    sudo make &>/tmp/redis.log
    sudo make install &>/tmp/redis.log
    printf "Done\n"
fi

# make directories for redis
# see "Installing Redis more properly" at http://redis.io/topics/quickstart
sudo mkdir -p /etc/redis /var/redis /opt/redis

if [ ! -d /opt/minard ]; then
    sudo mkdir /opt/minard
    sudo chown $USER /opt/minard
fi

if [ ! -f /opt/minard/bin/activate ]; then
    # create virtual environment
    virtualenv --no-site-packages /opt/minard
fi

cd /opt/minard
source bin/activate

pip install -qq supervisor

if [ ! -d /opt/minard/src ]; then
    mkdir src
fi

if [ ! -d /opt/minard/src/minard ]; then
    printf "Installing minard..."
    cd $VIRTUAL_ENV/src
    git clone -q git@github.com:tlatorre-uchicago/minard.git
    pip install -qq ./minard
    cd minard/doc
    make html
    cp -r _build/html /opt/minard/www/static/doc
    printf "Done\n"
else
    printf "Updating minard..."
    cd $VIRTUAL_ENV/src/minard
    git pull
    cd doc
    make html &>/dev/null
    rm -rf /opt/minard/www/static/doc
    cp -r _build/html /opt/minard/www/static/doc
    cd $VIRTUAL_ENV/src
    yes | pip -qq uninstall minard
    pip -qq install ./minard
    printf "Done\n"
fi

if [ ! -d /opt/minard/src/disp ]; then
    printf "Installing disp..."
    cd $VIRTUAL_ENV/src
    git clone -q git@github.com:tlatorre-uchicago/disp.git
    cd disp
    make &>/tmp/disp.log
    echo 'export PYTHONPATH=$VIRTUAL_ENV/src/disp/python:$PYTHONPATH' >> $VIRTUAL_ENV/bin/activate
    echo 'export LD_LIBRARY_PATH=$VIRTUAL_ENV/src/disp/lib:$LD_LIBRARY_PATH' >> $VIRTUAL_ENV/bin/activate
    printf "Done\n"
else
    printf "Updating disp..."
    cd $VIRTUAL_ENV/src/disp
    git pull
    make clean &>/dev/null
    make &>/tmp/disp_install.log
    printf "Done\n"
fi

# make sure gunicorn user exists
if ! id -u gunicorn >/dev/null; then
    echo "Adding gunicorn user..."
    sudo useradd -r gunicorn
fi

# make sure snoplusmon user exists
if ! id -u snoplusmon >/dev/null; then
    echo "Adding snoplusmon user..."
    sudo useradd -r snoplusmon
fi

# make sure nginx user exists
if ! id -u nginx >/dev/null; then
    echo "Adding nginx user..."
    sudo useradd -r nginx
fi

# create /var/log/snoplus
sudo mkdir -p /var/log/snoplus
sudo chown snoplusmon:snoplusmon /var/log/snoplus

cd $VIRTUAL_ENV/src/minard

# install gunicorn init script
sudo cp init/gunicorn /etc/init.d/gunicorn

# add gunicorn service
add_service gunicorn

if [ -f /etc/debian_version ]; then
    sudo cp init/supervisord_debian /etc/init.d/supervisord
elif [ -f /etc/redhat-release ]; then
    sudo cp init/supervisord_redhat /etc/init.d/supervisord
else
    echo "Error! Couldn't determine Linux distribution!"
    echo "no /etc/debian_version or /etc/redhat-release file"
    exit 1
fi

add_service supervisord

sudo cp etc/supervisord.conf /etc/supervisord.conf

if [ -f /etc/debian_version ]; then
    sudo cp init/nginx_debian /etc/init.d/nginx
elif [ -f /etc/redhat-release ]; then
    sudo cp init/nginx_redhat /etc/init.d/nginx
else
    echo "Error! Couldn't determine Linux distribution!"
    echo "no /etc/debian_version or /etc/redhat-release file"
    exit 1
fi

add_service nginx

sudo cp etc/nginx.conf /etc/nginx/nginx.conf

# install redis init script
sudo cp init/redis_6379 /etc/init.d/redis_6379

# redis configuration file
# this is where, for example, the location of the backup image is configured
sudo cp etc/redis.conf /etc/redis/6379.conf

# add redis service
add_service redis_6379

