#!/bin/sh
#
# chkconfig: 345 91 19
# description: monitoring tools daemon init script

BIN=/opt/minard/bin
BUILDER_KEY=/etc/minard/id_rsa_builder

# make sure log directory exists
mkdir -p /opt/minard/log

sudo -u www-data nohup $BIN/minard_dispatch &>/opt/minard/log/minard_dispatch.log &
sudo -u www-data nohup $BIN/minard_builder $BUILDER_KEY &>/opt/minard/log/minard_builder.log &
sudo -u www-data nohup $BIN/orca_producer &>/opt/minard/log/orca_producer.log &
sudo -u www-data nohup $BIN/orca_consumer &>/opt/minard/log/orca_consumer.log &
