#!/bin/sh
#
# chkconfig: 345 91 19
# description: orca_producer daemon init script

NAME=orca_producer
CMD=/opt/minard/bin/$NAME
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
USER=snoplusmon

case "$1" in
    start)
        if [ -f $PIDFILE ]; then
            echo "$PIDFILE exists, process is already running or crashed"
        else
            echo "Starting $NAME daemon..."
            $CMD -d --logfile=$LOGFILE --pidfile=$PIDFILE --user=$USER
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]; then
            echo "$PIDFILE does not exist, process is not running"
        else
            PID=$(cat $PIDFILE)
            echo "Stopping..."
            kill $PID
            while [ -x /proc/${PID} ]; do
                echo "Waiting for $NAME to shutdown..."
                sleep 1
            done
        fi
        ;;
    reload|restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 start|stop|restart|reload"
        exit 1
esac
exit 0
