#!/bin/sh
#
# chkconfig: 345 91 19
# description: orca_producer daemon init script
### BEGIN INIT INFO
# Provides: orca_producer
# Required-Start: $network $local_fs $remote_fs
# Required-Stop: $network $local_fs $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Should-Start: $syslog $named
# Should-Stop: $syslog $named
# Short-Description: start and stop orca_producer
# Description: orca_producer daemon
### END INIT INFO

NAME=orca_producer
CMD=/opt/minard/bin/$NAME
PIDFILE=/var/run/minard/$NAME.pid
LOGFILE=/var/log/$NAME.log
USER=snoplusmon

case "$1" in
    start)
        if [ -f $PIDFILE ]; then
            echo "$PIDFILE exists, process is already running or crashed"
        else
            echo "Starting $NAME daemon..."
            $CMD -d --logfile=$LOGFILE --pidfile=$PIDFILE --user=$USER
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]; then
            echo "$PIDFILE does not exist, process is not running"
        else
            PID=$(cat $PIDFILE)
            echo "Stopping..."
            kill $PID
            while [ -x /proc/${PID} ]; do
                echo "Waiting for $NAME to shutdown..."
                sleep 1
            done
        fi
        ;;
    reload|restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 start|stop|restart|reload"
        exit 1
esac
exit 0
