#!/bin/bash
#
# chkconfig: 345 91 19
# description: Minard daemon init script

VIRTUAL_ENV=/venv/minard/
PIDFILE=/var/run/minard/minard.pid
LOGFILE=/var/log/minard.log

source $VIRTUAL_ENV/bin/activate

. /etc/init.d/functions

case "$1" in
    start)
        if [ -f $PIDFILE ]; then
            echo "$PIDFILE exists, process is already running or crashed"
        else
            echo "Starting workers daemon..."
            workers --pidfile=$PIDFILE &> $LOGFILE &
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]; then
            echo "$PIDFILE does not exist, process is not running"
        else
            echo "Stopping..."
            killproc -p $PIDFILE
            echo "Waiting for workers to shutdown..."
            sleep 1
        fi
        ;;
    reload|restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 start|stop|restart|reload"
        exit 1
esac
exit 0
