#!/usr/bin/env python
from __future__ import division
from minard.orca import orca_consumer

if __name__ == '__main__':
    import argparse
    from multiprocessing import Process

    parser = argparse.ArgumentParser('ORCA stream consumer')
    parser.add_argument('-w', type=int, default=2, help='number of workers')
    args = parser.parse_args()

    workers = []
    for i in range(args.w):
        p = Process(target=orca_consumer,args=(5557,))
        p.start()
        workers.append(p)
        p = Process(target=orca_consumer,args=(5558,))
        p.start()
        workers.append(p)

    for worker in workers:
        worker.join()
