#!/usr/bin/env python
from minard.orca import orca_producer

if __name__ == '__main__':
    import argparse
    import time
    import sys

    parser = argparse.ArgumentParser('ORCA stream producer')
    parser.add_argument('--host',default='daq1.sp.snolab.ca')
    parser.add_argument('--port',default=44666,type=int)
    args = parser.parse_args()

    while True:
        try:
            orca_producer(args.host,args.port)
        except Exception as e:
            sys.stderr.write(str(e) + '\n')

        time.sleep(10)
