# List of all nearline job types
jobTypes = ["All","DAQ","SMELLIE","BLINDNESS_CHUNKER","PCATELLIE","RUN","TELLIE","ECA","PING_CRATES","PMTCalStatus","ANALYSIS","DQHL","CHS","DQLL","PMTNOISE","CHANNEL_FLAGS","CLOCK_JUMPS", "TRIGGER_OCCUPANCY"]

